# Generated by Django 4.1.1 on 2022-09-24 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('price', models.CharField(blank=True, max_length=100, null=True, verbose_name='price')),
                ('class_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='class')),
                ('image', models.ImageField(upload_to='Images/%d%m%y')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='Varients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='title')),
                ('availableStock', models.CharField(blank=True, max_length=100, null=True, verbose_name='availableStock')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.product')),
            ],
        ),
    ]
