# Generated by Django 4.1.1 on 2022-09-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='name'),
        ),
    ]
