# Generated by Django 4.1.1 on 2022-09-24 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='varients',
            old_name='user_id',
            new_name='product_name',
        ),
    ]
